### PR TITLE
Fixes #2: Embed Youtube video

### LINKED ISSUE #2: Embed demo video in README.asciidoc
It would be nice to have your demo video embedded in your README.asciidoc file

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Comment by gastaldi** [comment]
Looks like the video is still not embedded. Checking

**Comment by gastaldi** [comment]
It works in AsciidocFX

**Comment by rmpestano** [comment]
I also have to update the video

**Comment by rmpestano** [comment]
Looks like github doesn't support videos embbedings in readme. I had to use an image to represent the video and redirect to youtube.

Thank you George!

**Pull request merged**
